pin_bitcoins/config/routes.rb
PinBitcoins::Application.routes.draw do
  resources :users
  
  root "home#index" 

  resources :home  do
    member do
      get 'generate_addr'
      get 'bet_on'
    end
  end

  match 'signup', to: 'users#new', as: 'signup', via: [:get, :post]
  match 'signin', to: 'users#signin', as: 'signin', via: [:get, :post]
  match 'authenticate_user', to: 'users#authenticate_user', as: 'authenticate_user', via: [:get, :post]
  match '/signout',to: 'users#signout',via: :delete
  match 'signout',to: 'users#signout',via: :delete
  match 'bit_addr_info',to: 'home#bit_addr_info',as: 'bit_addr_info',  via: [:get, :post]
  match 'bet_existing',to: 'home#bet_existing',as: 'bet_existing',  via: [:get, :post]
  match 'bet_new',to: 'home#bet_new',as: "bet_new",  via: [:get, :post]
  match 'bet_create',to: 'home#bet_create',as: "bet_create",  via: [:get, :post]

  

end

pin_bitcoins/app/models/bet.rb
class Bet < ActiveRecord::Base
  validates_presence_of :description ,:amount
  serialize :betbetween, Array
  belongs_to :user
end

pin_bitcoins/app/models/bitcoin_info.rb
class BitcoinInfo < ActiveRecord::Base
  belongs_to :user
end

pin_bitcoins/app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name,:email,:password
  has_many :bitcoin_infos
  has_many :bets
end

pin_bitcoins/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

pin_bitcoins/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

  end

  def generate_addr
    @key = Bitcoin::generate_key
    @address = Bitcoin::pubkey_to_address(@key[1])
    @bitcoin_info = BitcoinInfo.create({
                                         :bit_address => @address,
                                         :priv_key => @key[0],
                                         :pub_key => @key[1],
                                         :user_id => current_user.id
                                       })
    if  @bitcoin_info.save
      @bitcoin_inf = BitcoinInfo.where(:user_id => current_user.id)
      respond_to do |format|
        format.html
        format.js  {@bitcoin_inf}
      end
    else
      flash[:danger] = @bitcoin_info.errors.full_messages
    end
  end

  def bit_addr_info
    @bitcoin_inf = BitcoinInfo.where(:user_id => current_user.id)
  end

  def bet_existing
     @bet = Bet.all
  end

  def bet_new
   
  end 

  def bet_create
    @bet = Bet.create({:description => params[:bet][:description],
                       :amount => params[:bet][:amount],
                       :date_of_bet => params[:bet][:date_of_bet],
                       :bet_creater_id => current_user.id
                      })
    if @bet.save
        flash[:success] = "Bet created successfully"
        redirect_to root_url
    else
      flash[:danger] = @bet.errors.full_messages
      redirect_to :bet_new
      #render json:
    end 
  end

  def bet_on
    @bet = Bet.find_by_id(params[:id])
    @bet.betbetween << current_user.id
    @bet.save
  end

end

pin_bitcoins/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, flash[:success]=> 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def signin

  end  

  def authenticate_user
    user = User.find_by({:email => params[:user][:email].downcase,:password=>params[:user][:password]})
    if user #&& user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      sign_in user.id
      redirect_to root_url
    else
     flash.now[:danger] = 'Invalid email/password combination'
     render :signin
    end
  end

  def signout
    sign_out
    redirect_to root_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

pin_bitcoins/app/helpers/application_helper.rb
module ApplicationHelper
end

pin_bitcoins/app/helpers/home_helper.rb
module HomeHelper
end

pin_bitcoins/app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    user = User.find_by_id(user)
    cookies.permanent[:user_id] = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def current_user?(user)
    user == current_user
  end
  
  def sign_out
    session[:user_id] = nil
    cookies.delete(:user_id)
  end

end  

pin_bitcoins/app/helpers/users_helper.rb
module UsersHelper
end

pin_bitcoins/app/views/home/bet_existing.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Current Bets</h3>
    </div>
    <div class="panel-body">
        <table class="table">
            <thead>
            <tr>
              <th>Description</th>
              <th>Amount</th>
              <th>Creater</th>
              <th>Date</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
                <%@bet.each do  |b|%>
                  <tr>
                    <td><%=b.description%></td>
                    <td><%=b.amount%> Bitcoins</td>
                    <td><%@user = User.find_by_id(b.bet_creater_id)%><%=@user.name%></td>
                    <td><%=b.date_of_bet%></td>
                    <td>
                      <%if current_user != @user%>
                         <%= link_to 'Bet',:method => 'get',:action => 'bet_on' ,:id=>b.id,:remote => true,:format => :js %>
                      <%end%>
                    </td>
                  </tr>
                <% end %>
            </tbody>
        </table>
    </div>
  </div>
</div>

pin_bitcoins/app/views/home/bet_new.html.erb
<div class="container">
  <div class="simple-box"> 
    <h2 class="form-signin-heading">Create New Bet</h2>
    <%= form_for(:bet,url: bet_create_path,:class=>"form-signin") do |f|%>
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description ,:class =>'form-control'%>
      </div>
      <div class="field">
        <%= f.label :amount %><br>
        <%= f.number_field :amount ,:class =>'form-control'%>
      </div>
      <div class="field">
        <%= f.label :date_of_bet %><br>
        <%= f.date_field :date_of_bet ,:class =>'form-control'%>
      </div>  
      <div class="actions" style="margin-top:20px;">
        <%= f.submit 'Create Bet',:class => "btn btn-success btn-lg btn-block"%>
      </div>

    <% end %>
  </div>
</div>    

pin_bitcoins/app/views/home/bit_addr_info.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Bitcoin Addresses</h3>
    </div>
    <div class="panel-body">
      <%= link_to "Generate Bitcoin Address", "home/1/generate_addr.js", :remote => true , :id => "genAddr",:class=>"btn btn-primary" %>
      <table class="table" id="bit_table">
      <thead>
      <tr>
        <th>Address</th>
        <th>Recieved</th>
        <th>Confirmed</th>
        <th>Generated</th>
      </tr>
      </thead>
      <tbody>
          <% @bitcoin_inf.each do |b| %>
            <tr>
                <td><%=b.bit_address%></td>
                <td>0.00</td>
                <td>0.00</td>
                <td><%=time_ago_in_words(b.created_at)%> ago</td>
            </tr>
          <%end%>
      </tbody>
     </table>
    </div>
  </div>
</div>
<script>
    $(document).ready(function() {
        $('#genAddr').bind('ajax:complete', function(event, data) {
            $('#bit_table').html(data.responseText);
        });
    });
</script>

pin_bitcoins/app/views/home/generate_addr.js.erb
<table class="table">
                <thead>
                    <tr>
                        <th>Address</th>
                        <th>Recieved</th>
                        <th>Confirmed</th>
                        <th>Generated</th>
                    </tr>
                </thead>
                <tbody>
                <% @bitcoin_inf.each do |b| %>
                    <tr>
                        <td><%=b.bit_address%></td>
                        <td>0.00</td>
                        <td>0.00</td>
                        <td><%=time_ago_in_words(b.created_at)%> ago</td>
                    </tr>
                <%end%>
                </tbody>
</table>

pin_bitcoins/app/views/home/index.html.erb
  <% if current_user%>
    <div class="jumbotron">
      <div class="container center">
        <h2>Hi ,<strong><%=current_user.name%>!</strong></h2>
        <h3>Pin Bitcoin is a website where you can bet bitcoins on real world events. There are two ways to earn bitcoins:</h3>

        <div>
            <%= link_to 'Bet On Existing' ,bet_existing_path,:class=> "btn btn-lg btn-primary"%>
            <%= link_to 'Create a new Bet' ,bet_new_path,:class=> "btn btn-lg btn-primary"%>
        </div>
      </div>
    </div>
    <div>
      <%= render 'current_bets' %>
    </div>
  <%else%>
    <div class="jumbotron">
      <div class="container center">
        <h1>Welcome</h1>
        <p>Plase sign up to continue </p>
        <%= link_to 'Sign Up >>' ,signup_path ,:class=> "btn btn-lg btn-primary"%>
      </div>
    </div>
  <%end%>

pin_bitcoins/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PinBitcoins</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Pin Bitcoins</a>
      <div class="nav-inner"> 
        <ul class="nav pull-right navbar-nav">
          <li><%= link_to "Home", root_path %></li>
            <% if current_user %>
              <li><%= link_to 'Bet' ,bet_existing_path%></li>
              <li><%= link_to 'Bit Addresses' ,bit_addr_info_path%></li>
              <li><%= link_to "Profile", edit_user_path(current_user.id)  %></li>
              <li><%= link_to "Sign out", signout_path, method: "delete"  %></li>
            <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
              <li><%= link_to "Sign up", signup_path %></li>
            <% end %>
        </ul>
      </div>
  </div>  
</div>
<div class="container">
    <% flash.each do |key, value| %>
       <%st =value.kind_of?String %>
         <%if key.to_s=="danger" && !st %>
          <div class="alert alert-<%= key %>">
              <ul>
                <% value.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
          </div>
         <% else %>
          <div class="alert alert-<%= key %>"><%= value %></div>
         <% end %>
    <% end %>
<%= yield %>
</div>
</body>
</html>

pin_bitcoins/app/views/users/_form.html.erb
<%= form_for(@user,:class=>"form-signin") do |f|%>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name ,:class =>'form-control'%>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email ,:class =>'form-control'%>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password ,:class =>'form-control'%>
  </div>
  <div class="actions" style="margin-top:20px;">
    <%= f.submit @user.new_record? ? "Create my account" : "Update my account",:class => "btn btn-success btn-lg btn-block"%>
  </div>

<% end %>

pin_bitcoins/app/views/users/edit.html.erb
<div class="container">
  <h2 class="form-signin-heading">Update Profile</h2>
  <div class="simple-box">
    <%= render 'form' %>
  </div>
</div>

pin_bitcoins/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

pin_bitcoins/app/views/users/new.html.erb
<div class="container">
	<h2 class="form-signin-heading">Sign Up</h2>
<div class="simple-box"> 
	<%= render 'form' %>
</div>    
	<%= link_to 'Back', users_path %>
</div>

pin_bitcoins/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

pin_bitcoins/app/views/users/signin.html.erb
<div class="container">
  <h2 class="form-signin-heading">Sign In</h2>
  <div class="simple-box"> 
  <%= form_for(:user,url: authenticate_user_path,:class=>"form-signin") do |f|%>
      <div class="field">
        <%= f.label :email %><br/>
        <%= f.text_field :email ,:class =>'form-control',:class =>'form-control'%>
      </div>
      <div class="field">
        <%= f.label :password %><br/>
        <%= f.password_field :password ,:class =>'form-control'%><br>
      </div>
      <div class="actions">   
        <%= f.submit "Sign In", class: "btn btn-primary btn-lg btn-block" %>
      </div>         
  <% end %>
  </div>    
</div>